### ISSUE TITLE
Can not work in the Ubuntu 20.04

### ISSUE THREAD

**Issue by HUANG-Haolun** [luooooob/vscode-asoul-notifications#44]
不起作用，我觉得需要一些权限吧
![2021-10-19 22-04-59 的屏幕截图](https://user-images.githubusercontent.com/72869392/137926573-08705ce8-b57f-4e59-aa1b-498c8beeafb2.png)

**Comment by luooooob** [comment]
你这个截图不会是把 members 删光了吧，你可以试试把自己的 uid 写上去然后自己发一条试试，会有一点延迟

**Comment by HUANG-Haolun** [comment]
我试了还是不行，我觉得应该是ubuntu需要设置一些权限吧，member没有截图是因为删了几位怕被你们鲨
![1634063879868](https://user-images.githubusercontent.com/72869392/138065144-668fecb6-e244-4317-9eb0-a579056d1dea.png)
