### ISSUE TITLE
只提示直播，不提示新动态和抖音

### ISSUE THREAD

**Issue by GunBusterNoLIKo** [luooooob/vscode-asoul-notifications#69]
安装完小助手后，没有进行任何设置时，不提示动态、抖音，直播是否提示不清楚。
在settings.json中加入如下代码后：
"asoulNotifications.asoulMembers": [
        {
            "nickname": "向晚",
            "bilibiliId": 672346917,
            "douyinId": "MS4wLjABAAAAxOXMMwlShWjp4DONMwfEEfloRYiC1rXwQ64eydoZ0ORPFVGysZEd4zMt8AjsTbyt"
        },
        {
            "nickname": "贝拉",
            "bilibiliId": 672353429,
            "douyinId": "MS4wLjABAAAAlpnJ0bXVDV6BNgbHUYVWnnIagRqeeZyNyXB84JXTqAS5tgGjAtw0ZZkv0KSHYyhP"
        },
        {
            "nickname": "珈乐",
            "bilibiliId": 351609538,
            "douyinId": "MS4wLjABAAAAuZHC7vwqRhPzdeTb24HS7So91u9ucl9c8JjpOS2CPK-9Kg2D32Sj7-mZYvUCJCya"
        },
        {
            "nickname": "嘉然",
            "bilibiliId": 672328094,
            "douyinId": "MS4wLjABAAAA5ZrIrbgva_HMeHuNn64goOD2XYnk4ItSypgRHlbSh1c"
        },
        {
            "nickname": "乃琳",
            "bilibiliId": 672342685,
            "douyinId": "MS4wLjABAAAAxCiIYlaaKaMz_J1QaIAmHGgc3bTerIpgTzZjm0na8w5t2KTPrCz4bm_5M5EMPy92"
        },
        {
            "nickname": "A-SOUL_Official",
            "bilibiliId": 703007996,
            "douyinId": "MS4wLjABAAAAflgvVQ5O1K4RfgUu3k0A2erAZSK7RsdiqPAvxcObn93x2vk4SKk1eUb6l_D4MX-n"
        }
    ],
    "asoulNotifications.bilibiliDynamics.enabled": true,
    "asoulNotifications.bilibiliLiveStatus.enabled": true,
    "asoulNotifications.douyinVideos.enabled": true,
会提示直播，动态和抖音不提示。在加入我自己的b站uid进行测试后：
"asoulNotifications.asoulMembers": [
        {
            "nickname": "向晚",
            "bilibiliId": 672346917,
            "douyinId": "MS4wLjABAAAAxOXMMwlShWjp4DONMwfEEfloRYiC1rXwQ64eydoZ0ORPFVGysZEd4zMt8AjsTbyt"
        },
        {
            "nickname": "贝拉",
            "bilibiliId": 672353429,
            "douyinId": "MS4wLjABAAAAlpnJ0bXVDV6BNgbHUYVWnnIagRqeeZyNyXB84JXTqAS5tgGjAtw0ZZkv0KSHYyhP"
        },
        {
            "nickname": "珈乐",
            "bilibiliId": 351609538,
            "douyinId": "MS4wLjABAAAAuZHC7vwqRhPzdeTb24HS7So91u9ucl9c8JjpOS2CPK-9Kg2D32Sj7-mZYvUCJCya"
        },
        {
            "nickname": "嘉然",
            "bilibiliId": 672328094,
            "douyinId": "MS4wLjABAAAA5ZrIrbgva_HMeHuNn64goOD2XYnk4ItSypgRHlbSh1c"
        },
        {
            "nickname": "乃琳",
            "bilibiliId": 672342685,
            "douyinId": "MS4wLjABAAAAxCiIYlaaKaMz_J1QaIAmHGgc3bTerIpgTzZjm0na8w5t2KTPrCz4bm_5M5EMPy92"
        },
        {
            "nickname": "A-SOUL_Official",
            "bilibiliId": 703007996,
            "douyinId": "MS4wLjABAAAAflgvVQ5O1K4RfgUu3k0A2erAZSK7RsdiqPAvxcObn93x2vk4SKk1eUb6l_D4MX-n"
        },
        {
            "nickname": "我",
            "bilibiliId": 13265958
        }
    ],
也不会提示我新发的动态。
我该怎么样才能让小助手提醒我😭救救孩子

**Comment by luooooob** [comment]
很抱歉……才发现之前发版的时候写错了一点东西，所以这个功能一直都是bug 的（居然到现在才有人发现，我自己也忘了）
现在的最新版已经修好了
如果没有自动更新，插件列表栏的每个插件右边都有个小齿轮，你点一下选择 install another version, 然后选 0.8.1 即可

**Comment by luooooob** [comment]
抖音的接口之前总是遇到问题，我不确定能不能用，bilibili 的已经试过可以了

**Comment by GunBusterNoLIKo** [comment]
b站动态提醒实测可用，感谢😘

> 抖音的接口之前总是遇到问题，我不确定能不能用，bilibili 的已经试过可以了
