### ISSUE TITLE
使用提醒小助手时vs code时不时卡顿

### ISSUE THREAD

**Issue by GunBusterNoLIKo** [luooooob/vscode-asoul-notifications#79]
近几天使用vs code时，经常时不时卡顿，卡顿时vs code占用的内存能暴涨到1g。
按照网络上的解决办法设置后，还是卡顿。
之后我在逐一检查扩展的时候，发现禁用提醒小助手后，vs code就不再卡顿，内存也降至400-600mb。

一个猜想，不一定对，可能是vs code更新1.63.1版本导致的卡顿。具体出现卡顿的时间我也记不清了，好像是我更新了1.63.1版本之后。

**Comment by luooooob** [comment]
这种偶然出现的内存爆炸实在无法排查。另见 https://github.com/luooooob/vscode-asoul-notifications/issues/85#issue-1086640525
